### ISSUE TITLE
CLI client doesn't connect to the network

### ISSUE THREAD

**Issue by cbruguera** [sovrin-foundation/sovrin-client#39]
I'm running `sovrin-client` version `0.1.15`.

Just when I run the `sovrin` command, no info about the nodes is shown in any moment. After I `connect test`, it looks like it doesn't really connect. 

After typing the `status` command, the client responds with "Attempting connection to test Sovrin network", but nothing more. It never really gets connected.

**Comment by lovesh** [comment]
@cbruguera Can you please upgrade your client like this `pip install -U --no-cache-dir sovrin-client`?

**Comment by cbruguera** [comment]
Still the same.

This is the message it displays after I `connect test`:
```
Saved keyring "Default" restored (/home/carlos/.sovrin/keyrings/test/default.wallet)
Active keyring set to "Default"
Client sovrinZ46sHJ found an empty node registry:
Active client set to sovrinZ46sHJ
A5EcnLwBKPnoE6Rj6FQ2Se3M2EFF5jU3iDy4p9xAwyEz listening for other nodes at 0.0.0.0:8272
```

**Comment by cbruguera** [comment]
(But after typing `status`, it's always "attempting...")

**Comment by dsanchezseco** [comment]
I cannot either and I used `pip install -U --no-cache-dir sovrin-client` to installed.

This is prompted after a `connect test`
```2UPccmYaPMN7QYzeqtFytxgWooPc8EiYknZNxT92yLAt looking for EvernymV2C at 52.38.24.189:9724
2UPccmYaPMN7QYzeqtFytxgWooPc8EiYknZNxT92yLAt looking for BULLDOGC at 52.56.74.57:9747
2UPccmYaPMN7QYzeqtFytxgWooPc8EiYknZNxT92yLAt looking for WSECUC at 40.121.149.41:9726
2UPccmYaPMN7QYzeqtFytxgWooPc8EiYknZNxT92yLAt looking for BYUC at 54.193.6.155:9745
2UPccmYaPMN7QYzeqtFytxgWooPc8EiYknZNxT92yLAt looking for FCUC at 69.144.146.171:9734
2UPccmYaPMN7QYzeqtFytxgWooPc8EiYknZNxT92yLAt looking for RespectNetworkC at 54.173.9.185:9730
2UPccmYaPMN7QYzeqtFytxgWooPc8EiYknZNxT92yLAt disconnected node EvernymV1C is joined
```
This output is repeated all the time non-stop

**Comment by cbruguera** [comment]
The issue was solved for me. My `pool_transactions_sandbox` file was empty. Therefore, no node info was being read.

[A related issue was reported in the forum](http://forum.sovrin.org/t/pool-transactions-file-not-found-root-sovrin-pool-transactions-sandbox/176/4).

**Comment by lovesh** [comment]
@dsanchezseco We have taken down our testing sandbox for maintenance. We will post an update here as soon as at is back online.

**Comment by JazzC** [comment]
I'm using the Docker Sovrin image to go through the "Alice" exercise. I'm able to connect to the test network (ALICE@test>) and it appears to search (9ymhcUf2SNSgw14s9BnzcCEYcKEcoqpA4qKhaWChHKN3 looking for BYUC at 54.193.6.155:9745) but it won't link, sync or accept the invitation because it says it needs to connect.
------------------------------
9ymhcUf2SNSgw14s9BnzcCEYcKEcoqpA4qKhaWChHKN3 looking for BYUC at 54.193.6.155:9745
Alice@test> accept invitation from Faber
Expanding Faber to "Faber College"
Invitation not yet verified.
Link not yet synchronized.
Invitation acceptance aborted.
Cannot sync because not connected. Please connect first.

Usage:
    connect <test|live>

9ymhcUf2SNSgw14s9BnzcCEYcKEcoqpA4qKhaWChHKN3 looking for FCUC at 69.144.146.171:9734
Alice@test> 

--------------------------------------------------------

**Comment by dhh1128** [comment]
Any ideas, @lovesh ?

**Comment by JazzC** [comment]
I think the reason for it not syncing is because Faber is not on the test network. Otherwise it would have worked. Am I right? But, if that is the case, how could I accept the invitation? Is that hard coded somewhere for demo purposes?

**Comment by JazzC** [comment]
Are the names for the Validators supposed to have a "C"? ex.9ymhcUf2SNSgw14s9BnzcCEYcKEcoqpA4qKhaWChHKN3 looking for **FCUC** at 69.144.146.171:9734

**Comment by dhh1128** [comment]
No, names of validators do not need to have a C at the end. That's just a coincidence.

**Comment by JazzC** [comment]
I apologize, I wasn't clear. What I mean to say is, the alias in the string for the validator in the pool_transaction_sandbox file doesn't have a "C" on the end (e.g., BYU), but they do show a "C" on the end when the client is pinging (e.g, 9ymhcUf2SNSgw14s9BnzcCEYcKEcoqpA4qKhaWChHKN3 looking for BYU*C* at 69.144.146.171:9734) 

That looked suspicious to me because it is like that for each validator and the next word in the pool_transaction_sandbox string for each one is "client_ip". Could there be a parsing issue?

**Comment by lovesh** [comment]
@JazzC Each Validator has 2 listeners, one for other Validators and one for clients, this makes it a little easier to scale our system. The listener for clients has the letter **C** appended to the node's name. That is why for **FCU** you see client trying to connect to **FCUC**. Also if you see in the pool ledger you will for each node we have 2 IP+port named as `node_ip`, `node_port` and `client_ip` and `client_port`. Currently the IPs are same as both listeners are using the same machine but we can change that to make them use different machines/network interfaces

**Comment by cbruguera** [comment]
The original error was fixed, so I intend to close this issue. @JazzC, was your problem fixed as well?

**Comment by JazzC** [comment]
Yes.
